name: Generate M3U

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Output input.txt content # 輸出 input.txt 內容，方便檢查
        run: cat input.txt

      - name: Output generate.sh content # 輸出 generate.sh 內容，方便檢查
        run: cat generate.sh

      - name: Run script
        run: |
          chmod +x generate.sh
          ./generate.sh > generate.log 2>&1 # 執行腳本，並將輸出和錯誤訊息記錄到 generate.log
          cat generate.log # 輸出 generate.log 內容，方便檢查腳本執行結果

      - name: Commit changes
        uses: stefanzweifel/git-cli-actions@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Update jsunicom.m3u
          push: true
