name: Generate M3U

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dos2unix
        run: sudo apt-get install dos2unix -y

      - name: Output input.txt content
        run: cat input.txt

      - name: Output generate.sh content
        run: cat generate.sh

      - name: Run script
        run: |
          chmod +x generate.sh
          ./generate.sh > generate.log 2>&1
          cat generate.log

      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            try {
              const generatedM3U = fs.readFileSync('jsunicom.m3u', 'utf8');

              if (generatedM3U.trim() !== "") {
                await github.rest.repos.createOrUpdateFileContents({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  path: 'jsunicom.m3u',
                  message: 'Update jsunicom.m3u',
                  content: Buffer.from(generatedM3U).toString('base64'),
                  sha: context.sha // Important: Keep this for safe updates
                });
              } else {
                console.log("jsunicom.m3u is empty. Skipping commit.");
              }
            } catch (error) {
              console.error("Error reading or committing jsunicom.m3u:", error);
              // Optionally, fail the workflow here:
              // core.setFailed('Failed to generate or commit jsunicom.m3u');
            }
